services:
  postgres:
    image: postgres:16
    container_name: daily_tracker_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: daily_tracker_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build: ./backend
    container_name: daily_tracker_backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - postgres
    env_file:
      - ./backend/.env

  strapi:
      build: ./cms
      container_name: daily_tracker_strapi
      environment:
        DATABASE_CLIENT: postgres
        DATABASE_HOST: postgres
        DATABASE_PORT: 5432
        DATABASE_NAME: daily_tracker_db
        DATABASE_USERNAME: postgres
        DATABASE_PASSWORD: postgres
      ports:
        - "1337:1337"
      volumes:
        - ./cms:/opt/app
        - /opt/app/node_modules
      depends_on:
        - postgres

volumes:
  postgres_data: